name: groundingdino
channels:
  - pytorch
  - nvidia
  - defaults
dependencies:
  - pip
  - python
  - pytorch
  - torchvision
  - pytorch-cuda
  - pip:
    - anyio
    - click
    - fastapi
    - h11
    - huey
    - idna
    - opencv-python
    - pydantic
    - pymemcache
    - requests
    - sniffio
    - starlette
    - uvicorn
    - transformers
    - supervision
    - segment-anything
    - psutil
    - git+https://github.com/IDEA-Research/GroundingDINO.git

  
